### ISSUE TITLE
微软发布 Windows Terminal

### ISSUE THREAD

**Issue by x-cold** [txd-team/monthly#46]
微软正在推出一款名为 Windows Terminal 的新命令行终端工具。它被设计为访问 PowerShell、 Cmd 和 Windows Linux 子系统（WSL）等环境。微软正在为想要调整终端工具的开发人员添加多个选项卡、分割窗口、快捷键支持，另外支持主题和自定义等等。微软这款新的 Windows 终端应用程序在 Build 2019 开发者大会上公布了。

https://devblogs.microsoft.com/commandline/introducing-windows-terminal/
https://github.com/microsoft/Terminal

**Comment by damujiangr** [comment]
Adopted
